import { NextResponse } from 'next/server';

// Cache untuk menghindari terlalu banyak request ke API eksternal
let cache: {
  hargaPerGram: number;
    goldUSD: number | null;
      usdToIdr: number | null;
        source: string;
          timestamp: number;
          } | null = null;

          // Cache berlaku selama 1 jam
          const CACHE_DURATION = 60 * 60 * 1000;

          // Harga fallback (akan diperbarui secara berkala dari API)
          const FALLBACK_HARGA = 1850000; // Rp 1.850.000/gram (estimasi 2025-2026)
          const TROY_OZ_TO_GRAM = 31.1035;

          async function fetchGoldPrice(): Promise<{
            hargaPerGram: number;
              goldUSD: number | null;
                usdToIdr: number | null;
                  source: string;
                  }> {
                    // Coba sumber 1: Open Exchange Rates + Metals API (gratis)
                      try {
                          // Ambil kurs USD ke IDR dari Frankfurter (European Central Bank)
                              const fxResponse = await fetch(
                                    'https://api.frankfurter.app/latest?from=USD&to=IDR',
                                          { next: { revalidate: 3600 } }
                                              );

                                                  if (!fxResponse.ok) throw new Error('FX API gagal');
                                                      const fxData = await fxResponse.json();
                                                          const usdToIdr: number = fxData.rates?.IDR;

                                                              if (!usdToIdr || usdToIdr < 10000) throw new Error('Kurs IDR tidak valid');

                                                                  // Ambil harga emas XAU/USD dari metals-api.com (free tier)
                                                                      // Alternatif: gunakan goldprice.org atau data.nasdaq.com
                                                                          const goldResponse = await fetch(
                                                                                'https://api.metals.live/v1/spot/gold',
                                                                                      { next: { revalidate: 3600 } }
                                                                                          );

                                                                                              if (!goldResponse.ok) throw new Error('Gold API gagal');
                                                                                                  const goldData = await goldResponse.json();
                                                                                                      
                                                                                                          // metals.live mengembalikan harga dalam USD per troy ounce
                                                                                                              const goldUsdPerOz: number = Array.isArray(goldData) 
                                                                                                                    ? goldData[0]?.price 
                                                                                                                          : goldData?.price || goldData?.gold;

                                                                                                                              if (!goldUsdPerOz || goldUsdPerOz < 100) throw new Error('Harga emas tidak valid');

                                                                                                                                  // Konversi: USD/troy oz -> IDR/gram
                                                                                                                                      const goldUsdPerGram = goldUsdPerOz / TROY_OZ_TO_GRAM;
                                                                                                                                          const hargaPerGram = Math.round(goldUsdPerGram * usdToIdr);

                                                                                                                                              if (hargaPerGram < 500000 || hargaPerGram > 5000000) {
                                                                                                                                                    throw new Error('Harga emas di luar rentang wajar');
                                                                                                                                                        }

                                                                                                                                                            return {
                                                                                                                                                                  hargaPerGram,
                                                                                                                                                                        goldUSD: goldUsdPerOz,
                                                                                                                                                                              usdToIdr,
                                                                                                                                                                                    source: 'metals.live + frankfurter.app (ECB)',
                                                                                                                                                                                        };
                                                                                                                                                                                          } catch (err1) {
                                                                                                                                                                                              console.warn('[gold-price] Sumber 1 gagal:', err1);
                                                                                                                                                                                                }

                                                                                                                                                                                                  // Coba sumber 2: goldprice.org API
                                                                                                                                                                                                    try {
                                                                                                                                                                                                        const fxResponse = await fetch(
                                                                                                                                                                                                              'https://api.frankfurter.app/latest?from=USD&to=IDR',
                                                                                                                                                                                                                    { next: { revalidate: 3600 } }
                                                                                                                                                                                                                        );
                                                                                                                                                                                                                            const fxData = await fxResponse.json();
                                                                                                                                                                                                                                const usdToIdr: number = fxData.rates?.IDR;

                                                                                                                                                                                                                                    // Gunakan Gold Price API alternatif
                                                                                                                                                                                                                                        const goldResponse = await fetch(
                                                                                                                                                                                                                                              'https://data-asg.goldprice.org/dbXRates/USD',
                                                                                                                                                                                                                                                    {
                                                                                                                                                                                                                                                            headers: {
                                                                                                                                                                                                                                                                      'User-Agent': 'Mozilla/5.0 (compatible; ZakatCalculator/1.0)',
                                                                                                                                                                                                                                                                              },
                                                                                                                                                                                                                                                                                      next: { revalidate: 3600 }
                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                );

                                                                                                                                                                                                                                                                                                    if (!goldResponse.ok) throw new Error('goldprice.org gagal');
                                                                                                                                                                                                                                                                                                        const goldData = await goldResponse.json();
                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                const goldUsdPerOz: number = goldData?.items?.[0]?.xauPrice || goldData?.xauPrice;

                                                                                                                                                                                                                                                                                                                    if (!goldUsdPerOz || !usdToIdr) throw new Error('Data tidak lengkap');

                                                                                                                                                                                                                                                                                                                        const goldUsdPerGram = goldUsdPerOz / TROY_OZ_TO_GRAM;
                                                                                                                                                                                                                                                                                                                            const hargaPerGram = Math.round(goldUsdPerGram * usdToIdr);

                                                                                                                                                                                                                                                                                                                                if (hargaPerGram < 500000 || hargaPerGram > 5000000) {
                                                                                                                                                                                                                                                                                                                                      throw new Error('Harga emas di luar rentang wajar');
                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                              return {
                                                                                                                                                                                                                                                                                                                                                    hargaPerGram,
                                                                                                                                                                                                                                                                                                                                                          goldUSD: goldUsdPerOz,
                                                                                                                                                                                                                                                                                                                                                                usdToIdr,
                                                                                                                                                                                                                                                                                                                                                                      source: 'goldprice.org + frankfurter.app (ECB)',
                                                                                                                                                                                                                                                                                                                                                                          };
                                                                                                                                                                                                                                                                                                                                                                            } catch (err2) {
                                                                                                                                                                                                                                                                                                                                                                                console.warn('[gold-price] Sumber 2 gagal:', err2);
                                                                                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                                                                                    // Fallback: gunakan harga hardcoded terbaru
                                                                                                                                                                                                                                                                                                                                                                                      return {
                                                                                                                                                                                                                                                                                                                                                                                          hargaPerGram: FALLBACK_HARGA,
                                                                                                                                                                                                                                                                                                                                                                                              goldUSD: null,
                                                                                                                                                                                                                                                                                                                                                                                                  usdToIdr: null,
                                                                                                                                                                                                                                                                                                                                                                                                      source: 'fallback-hardcoded',
                                                                                                                                                                                                                                                                                                                                                                                                        };
                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                        export async function GET() {
                                                                                                                                                                                                                                                                                                                                                                                                          try {
                                                                                                                                                                                                                                                                                                                                                                                                              // Cek cache
                                                                                                                                                                                                                                                                                                                                                                                                                  if (cache && Date.now() - cache.timestamp < CACHE_DURATION) {
                                                                                                                                                                                                                                                                                                                                                                                                                        const nisabEmas = 85 * cache.hargaPerGram;
                                                                                                                                                                                                                                                                                                                                                                                                                              return NextResponse.json({
                                                                                                                                                                                                                                                                                                                                                                                                                                      success: true,
                                                                                                                                                                                                                                                                                                                                                                                                                                              cached: true,
                                                                                                                                                                                                                                                                                                                                                                                                                                                      hargaPerGram: cache.hargaPerGram,
                                                                                                                                                                                                                                                                                                                                                                                                                                                              goldUSD: cache.goldUSD,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      usdToIdr: cache.usdToIdr,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              source: cache.source,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      timestamp: new Date(cache.timestamp).toISOString(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              nisab: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        emasGram: 85,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  nisabEmasRupiah: nisabEmas,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            nisabBulanan: Math.round(nisabEmas / 12),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  // Ambil harga terbaru
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      const result = await fetchGoldPrice();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          // Simpan ke cache
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              cache = {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ...result,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          timestamp: Date.now(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const nisabEmas = 85 * result.hargaPerGram;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      return NextResponse.json({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            success: true,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  cached: false,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        hargaPerGram: result.hargaPerGram,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              goldUSD: result.goldUSD,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    usdToIdr: result.usdToIdr,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          source: result.source,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                timestamp: new Date().toISOString(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      nisab: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              emasGram: 85,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      nisabEmasRupiah: nisabEmas,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              nisabBulanan: Math.round(nisabEmas / 12),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          } catch (err) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              console.error('[gold-price] Error:', err);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const nisabEmas = 85 * FALLBACK_HARGA;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      return NextResponse.json({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            success: false,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  cached: false,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        hargaPerGram: FALLBACK_HARGA,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              goldUSD: null,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    usdToIdr: null,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          source: 'fallback-error',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                timestamp: new Date().toISOString(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      nisab: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              emasGram: 85,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      nisabEmasRupiah: nisabEmas,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              nisabBulanan: Math.round(nisabEmas / 12),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }, { status: 200 });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }